name: Publish

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew build

    - uses: actions/upload-artifact@v4
      with:
        name: pv-addon-flashback
        path: |
          build/libs/*.jar
          !build/libs/*-@(sources).jar
